### ISSUE TITLE
Be able to set default value on the channel

### ISSUE THREAD

**Issue by maximehuran** [monsieurbiz/SyliusSettingsPlugin#57]
It could be nice to set default values on the channel scope.

```yaml
monsieurbiz_sylius_settings:
    plugins:
        app.my_plugin:
            vendor_name: Monsieur Biz
            vendor_url:
            plugin_name: My Plugin
            description: My amazing plugin
            icon: rocket
            use_locales: false
            classes:
                form: App\Form\Type\SettingsType
            default_values:
                value_1: 'value_1'
                value_2: 'value_2'
            MY_CHANNEL_CODE_values:
                value_1: 'value_1_1'
                value_2: 'value_2_2'
```

**Comment by jacquesbh** [comment]
Hi @maximehuran !

Your issue will be fixed by #60.

**Comment by maximehuran** [comment]
It's not the same as fixtures. Are fixtures the only way to do that ?

**Comment by maximehuran** [comment]
Maybe by changing the YAML format : 

```yaml
monsieurbiz_sylius_settings:
    plugins:
        app.my_plugin:
            vendor_name: Monsieur Biz
            vendor_url:
            plugin_name: My Plugin
            description: My amazing plugin
            icon: rocket
            use_locales: false
            classes:
                form: App\Form\Type\SettingsType
            default_values:
                default:
                    value_1: 'value_1'
                    value_2: 'value_2'
                MY_CHANNEL_CODE:
                    value_1: 'value_1_1'
                    value_2: 'value_2_2'
```
